# Generated by Django 4.2.13 on 2024-06-23 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.calendar')),
            ],
        ),
    ]
